### ISSUE TITLE
Obfuscating JS for getting refs 😂

### ISSUE THREAD

**Issue by AlexKrutoy** [MeoMunDep/GenkiMiner#2]
![изображение](https://github.com/user-attachments/assets/4edd9e67-4c83-44bd-bf10-60a95f537c51)
okay bro, obfuscate more

**Comment by MeoMunDep** [comment]
lol for who thief like you ?

my member in my group all know it?

they all have automation browser which can ref accounts, idiot, and i check ur shjtty github, LOL also making script, so why see mine? that the reason i obfuscate to prevent thief like u fk idiot, and not all ref feature all work, even i put out in configs files, u dont know shjt about how the game and telegram api work so stfu kiddo.

trashy kiddo like u always go around and steal everyone code

**Comment by MeoMunDep** [comment]
get a life kiddo

**Comment by MeoMunDep** [comment]
can deobfuscate code but cant even create ur own code LOL, try to do better kiddo, learn more

**Comment by MeoMunDep** [comment]
Not every thing in this world is free kiddo, at least im not try to give them botnet

**Comment by MeoMunDep** [comment]
Mày |\|gu vãi lo|\| =)))

**Comment by MeoMunDep** [comment]
Cái thằng ngu 17 tuổi ranh láo toét, học được dăm ba cái code oai cái db gì với ai? 

Cảm thấy mình giỏi thì cút ra group khác share code free mà ăn cắp, ranh con.
